### ISSUE TITLE
Support for Less

### ISSUE THREAD

**Issue by SebastianS90** [qodesmith/purgecss-whitelister#1]
It would be grat if this plugin could also parse `less` files. Right now the `postcss` parser executed in `list-css-selectors` throws an exception if you have a file with [line comments](http://lesscss.org/features/#features-overview-feature-comments) (`//`).

**Comment by qodesmith** [comment]
@SebastianS90 for some reason, I wasn't even watching my own repo so I never got notified of this issue! Anyways, I like your idea. Let me look into it. Perhaps I can make it detect the file (css, less, scss) and take it from there.

**Comment by qodesmith** [comment]
@SebastianS90 As an update, I've been working on this. Should see some light soon!

**Comment by qodesmith** [comment]
@SebastianS90 Ok my friend. Version 2.0 is out! Try it out. Works with css, sass, and less now!

**Comment by SebastianS90** [comment]
Thanks a lot!
