### ISSUE TITLE
throw new ParsingError(e, css) 

### ISSUE THREAD

**Issue by weilinzung** [qodesmith/purgecss-whitelister#10]
An example that if I have `*display: inline;` that with an asterisk symbol.  Then it would cause errors:

```
/project/node_modules/gonzales-pe/lib/gonzales.js:816
	    throw new ParsingError(e, css);
	    ^
Parsing error: Please check validity of the block starting from line #31
```

That CSS framework is from a very old version of: https://github.com/csswizardry/inuit.css/blob/master/objects/_nav.scss

**Comment by weilinzung** [comment]
looks like the CSS hacks issue.
https://github.com/tonyganch/gonzales-pe/issues/29

however, I import `purgecss-whiteloster` only with webpack usage. It is strange after adding this package, it would also affect some of my old projects that use another command line.

Both of the functions are inside of one file `main.js`, and each function is separated.
webpack -> new command line
gulp -> old command line

**Comment by weilinzung** [comment]
`!project-root/..../inuit.css/**` a workaround, ignore the folder.

**Comment by qodesmith** [comment]
@weilinzung  I'm not following at all. I see you closed the issue, but I'd like to know if this tool is causing an error.

**Comment by weilinzung** [comment]
@qodesmith 

It is the dependency cause issue: `gonzales-pe`. It does not support CSS hacks.

tonyganch/gonzales-pe#29
