### ISSUE TITLE
Error: Expecting punctuation: "}" (scss-parser)

### ISSUE THREAD

**Issue by chasegiunta** [qodesmith/purgecss-whitelister#7]
This looks to upstream, but noting the issue anyway in case there's an alternative library out there.

Getting `Error: Expecting punctuation: "}"` errors upon trying to whitelist a library.
Looks similar to https://github.com/salesforce-ux/scss-parser/issues/20

Not sure if that project is being updated anymore so:

Considering the 3rd party library file I'm reference is just a plain .css file (plyr video lib), maybe we can skip the scss parser altogether?

**Comment by qodesmith** [comment]
@chasegiunta Hmmm... Can you post the contents of the file you're trying to whitelist? I'll take a look.

**Comment by chasegiunta** [comment]
Sure. https://github.com/sampotts/plyr/blob/master/dist/plyr.css

**Comment by qodesmith** [comment]
@chasegiunta Ok, I see what's going on. I put the contents of the file into an "unminifier" [here](http://unminify.com/). It seems that all of the last declarations are missing semicolons which is causing things to break. I think CSS needs to have semi's after each declaration as per the spec.

**Comment by qodesmith** [comment]
Doing a bit more investigation shows that in fact the [last semicolon](https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax) in a block does _not_ need to be there, so clearly scss-parser is breaking with this. I wonder if there's a tool to sanitize it first and _then_ pass it through to scss-parser.

**Comment by chasegiunta** [comment]
Looks like some others have replaced scss-parser with https://github.com/tonyganch/gonzales-pe to resolve similar problems. Maybe that might be a better lib to address compatibilities?

**Comment by qodesmith** [comment]
@chasegiunta I've seen that tool. I'll try using it and see what happens.

**Comment by qodesmith** [comment]
@chasegiunta So it looks like gonzales-pe doesn't throw errors. I'm refactoring things to use this library under the hood and getting rid of scss-parser. I'll update & close this issue once that's done.

**Comment by chasegiunta** [comment]
@qodesmith awesome man. I dug into a little further and it definitely looks like both have their fair share of issues. Not sure there will be a perfect one out there, but it seems that gonzales-pe might have a bit more activity so hopefully less errors overall.

I still think, to reduce errors down the line with this library, you should only run gonzales-pe upon .scss files being input.

P.S. After visiting your site, I expect all your github issue responses from now on to be written out in sick rhymes and recorded back.

**Comment by qodesmith** [comment]
@chasegiunta Ok my friend. I was *this* close to implementing my own scss parser (which still may be a project for the future)! After going through the code for `scss-parser` and `gonzales-pe`, my brain was a bit fried. So I did the next best thing... used both! All things remain the same except if `scss-parser` fails, it tries to use `gonzales-pe`. If that fails, well, then we're all out of luck! Anyway, this should be good for now until one day I write my own scss parser. Let me know how things work out!
