### ISSUE TITLE
Add .pcss to the list of extensions

### ISSUE THREAD

**Issue by khalwat** [qodesmith/purgecss-whitelister#9]
Any chance we could get `pcss` added to the list of allowable file extensions?

**Comment by qodesmith** [comment]
@khalwat I've never heard of a `pcss` file. Care to enlighten me?

**Comment by khalwat** [comment]
PostCSS c.f.: https://twitter.com/PostCSS/status/973650168447946753

**Comment by qodesmith** [comment]
Adding the `.pcss` extension to the whitelist is the easy part. I'm just concerned about any syntax that the parsers this library is using won't recognize. More and more I feel I'm gonna have to write my own parser. I'm completely intimidated, lol. Let me look into `pcss` and make sure nothing will break.

**Comment by qodesmith** [comment]
@khalwat So it doesn't look like there's any official documentation for `pcss`. I'm gonna hold off on this unless more info surfaces.

**Comment by khalwat** [comment]
Any chance you could just add it to the list of allowable extensions, but tell people who use it that they are on their own? I've modified it locally and it works for my purposes, FWIW.

**Comment by khalwat** [comment]
Worst case I suppose I can just fork it and add the extension to the list. I'd prefer to see it part of the main repo tho, so things don't get out of sync.

**Comment by qodesmith** [comment]
@khalwat Yea, I could do that. I'll update that today and add something to the readme.

**Comment by qodesmith** [comment]
Done.

**Comment by khalwat** [comment]
Thank you!

**Comment by khalwat** [comment]
Confirmed it works like a treat!

**Comment by qodesmith** [comment]
@khalwat 💯
